import DataLineDataLine10resource_usage_specEController from '../data-line-data-line10-resource-usage-spec-e';

var DataLineDataLine10resource_usage_specENewController = DataLineDataLine10resource_usage_specEController;
export default DataLineDataLine10resource_usage_specENewController;
